name: Auto Tag Release and Update Composer

on:
  push:
    branches:
      - main  # or your default branch

permissions:
  contents: write  # This gives the GITHUB_TOKEN write access to repository contents

jobs:
  create-tag-and-update-composer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all tags and branches
      
      - name: Get latest tag
        id: get_latest_tag
        run: echo "LATEST_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT
      
      - name: Bump version and push tag
        id: tag_version
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: false

      - name: Update Composer version
        run: |
          NEW_VERSION="${{ steps.tag_version.outputs.new_tag }}"
          NEW_VERSION="${NEW_VERSION#v}"  # Remove 'v' prefix if present
          sed -i 's/"version": ".*"/"version": "'"${NEW_VERSION}"'"/' composer.json
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add composer.json
          git commit -m "Update Composer version to ${NEW_VERSION}"
          git push

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: |
            Changes in this Release
            - Updated Composer version to ${{ steps.tag_version.outputs.new_tag }}
            - Added management of maxTokens and temperature parameters
            - Other changes...
          draft: false
          prerelease: false
