name: Auto Tag Release and Update Composer

on:
  push:
    branches:
      - main  # or your default branch

permissions:
  contents: write  # This gives the GITHUB_TOKEN write access to repository contents

jobs:
  create-tag-and-update-composer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all tags and branches
      
      - name: Bump version and push tag
        id: tag_version
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: true
          DRY_RUN: true

      - name: Update Composer version
        run: |
          NEW_VERSION="${{ steps.tag_version.outputs.new_version }}"
          sed -i 's/"version": ".*"/"version": "'"${NEW_VERSION}"'"/' composer.json
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add composer.json
          git commit -m "Bump version to ${NEW_VERSION}"
          git tag -a "v${NEW_VERSION}" -m "Version ${NEW_VERSION}"
          git push && git push --tags

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.tag_version.outputs.new_version }}
          release_name: Release v${{ steps.tag_version.outputs.new_version }}
          body: |
            Changes in this Release
            - Updated Composer version to ${{ steps.tag_version.outputs.new_version }}
            - Other changes...
          draft: false
          prerelease: false
